#conda env update -p ./env
name: lclf
dependencies:
  - python=3.7.*
  - pip:
    - confluent_kafka
    - requests
    - fastavro
    - faust
    - httpx
    - python-schema-registry-client
    - cassandra-driver
    - avro
    - influxdb
    - python-rocksdb
    - aiomonitor==0.4.4
